# -*- mode: ruby -*-
# vi: set ft=ruby :

vms = {"192.168.100.101" => "node-1",
       "192.168.100.102" => "node-2",
       "192.168.100.103" => "node-3"}

Vagrant.configure("2") do |config|

  vms.each do |vm_ip, vm_name|

    config.vm.define vm_name do |node|

      node.vm.box_check_update = false
      node.vm.box = "bento/centos-7.4"
      node.vm.hostname = vm_name
      node.vm.network "private_network", ip: vm_ip
      # config.vm.synced_folder "../data", "/vagrant_data"

      node.vm.provider "virtualbox" do |v|
        # v.name = vm_name
        v.memory = 1048
        v.cpus = 1
      end

      node.vm.provision "shell", inline: <<-SHELL
        # 修改hostname       echo "#{vm_name}">/etc/hostname

        # 添加本地hosts解析
        for i in "#{vms.map{|k,v|"#{k}    #{v}"}.join('" "')}";do echo $i>>/etc/hosts;done

        # 删除hosts文件第一行
        sed -i '1d' /etc/hosts
      SHELL
      # node.ssh.private_key_path = ".setting/id_rsa"
      # node.ssh.username = "ifnoelse"
    end
  end
end